// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RailFenceAPI.Data;

namespace RailFenceAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230111190239_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RailFenceAPI.Entities.Desifrovanje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DesifrovanaRec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dubina")
                        .HasColumnType("int");

                    b.Property<string>("RecZaDesifrovanje")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Desifrovanja");
                });

            modelBuilder.Entity("RailFenceAPI.Entities.Sifrovanje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Dubina")
                        .HasColumnType("int");

                    b.Property<string>("RecZaSifrovanje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SifrovanaRec")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sifrovanja");
                });
#pragma warning restore 612, 618
        }
    }
}
